# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "J. Kenji López-Alt"
tagline:          "On the road in Asia and beyond…”
url:              http://kenjilopezalt.github.io/
paginate:         1
baseurl:          
author:
  name:           J. Kenji López-Alt
  url:            https://twitter.com/thefoodlab
  email:          kenji@seriouseats.com
